services:
  postgres:
    image: 'postgres:16'
    container_name: portfolio-db
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: wealth_user
      POSTGRES_PASSWORD: wealth_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: 'mongo:7.0'
    container_name: market-db
    environment:
      MONGO_INITDB_DATABASE: market_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  kafka:
    image: 'confluentinc/cp-kafka:7.6.0'
    container_name: event-broker
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: 'NjY0NmE0NjY0NmE0NjY0Ng=='
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    image: 'redis:alpine'
    container_name: gateway-cache
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  mongodb-data:
  kafka-data:
