spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: portfolio-service
              uri: ${PORTFOLIO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/portfolio/**
            - id: market-data-service
              uri: ${MARKET_DATA_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/market/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
                    key-resolver: "#{@ipKeyResolver}"
            - id: insight-service
              uri: ${INSIGHT_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/insight/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
