spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: portfolio-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/portfolio/**
            - id: market-data-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/market/**
            - id: insight-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/insight/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
