import type { SentimentSource } from "@/types/insights";

const LABELS: Record<SentimentSource, string> = {
  AZURE_OPENAI: "Generated by Azure OpenAI",
  BEDROCK: "Generated by Amazon Bedrock",
  RULE_BASED: "Rule-based text (no AI model)",
};

/**
 * The provenance line for sentiment text, derived only from the backend's declared source.
 * Returns null — make no claim — when the source is absent or not one this client knows.
 */
export function sentimentSourceLabel(source: SentimentSource | string | null | undefined): string | null {
  if (source == null) return null;
  return Object.prototype.hasOwnProperty.call(LABELS, source) ? LABELS[source as SentimentSource] : null;
}

const CHAT_LABELS: Record<SentimentSource, string> = {
  AZURE_OPENAI: "Sentiment generated by Azure OpenAI; price and change from stored market data",
  BEDROCK: "Sentiment generated by Amazon Bedrock; price and change from stored market data",
  RULE_BASED: "Rule-based sentiment (no AI model); price and change from stored market data",
};

/**
 * The provenance line under a chat reply. Unlike the insight card, whose label sits under the
 * sentiment text alone, a chat reply is mostly templated from stored prices with the sentiment
 * appended, so the label scopes the source to the sentiment (rehearsal defect #5). Null — no
 * claim — under the same conditions as {@link sentimentSourceLabel}.
 */
export function chatSentimentSourceLabel(source: SentimentSource | string | null | undefined): string | null {
  if (source == null) return null;
  return Object.prototype.hasOwnProperty.call(CHAT_LABELS, source) ? CHAT_LABELS[source as SentimentSource] : null;
}
