import { describe, expect, it } from "vitest";
import { sentimentSourceLabel } from "./sentimentSource";

describe("sentimentSourceLabel (rehearsal defect #5)", () => {
  it("names each declared source", () => {
    expect(sentimentSourceLabel("AZURE_OPENAI")).toBe("Generated by Azure OpenAI");
    expect(sentimentSourceLabel("BEDROCK")).toBe("Generated by Amazon Bedrock");
    expect(sentimentSourceLabel("RULE_BASED")).toBe("Rule-based text (no AI model)");
  });

  it.each([[null], [undefined], [""], ["OPENAI"], ["toString"], ["__proto__"]])(
    "makes no claim for %p",
    (source) => {
      expect(sentimentSourceLabel(source as string | null | undefined)).toBeNull();
    },
  );
});
