import type { SentimentSource } from "@/types/insights";

const LABELS: Record<SentimentSource, string> = {
  AZURE_OPENAI: "Generated by Azure OpenAI",
  BEDROCK: "Generated by Amazon Bedrock",
  RULE_BASED: "Rule-based text (no AI model)",
};

/**
 * The provenance line for sentiment text, derived only from the backend's declared source.
 * Returns null — make no claim — when the source is absent or not one this client knows.
 */
export function sentimentSourceLabel(source: SentimentSource | string | null | undefined): string | null {
  if (source == null) return null;
  return Object.prototype.hasOwnProperty.call(LABELS, source) ? LABELS[source as SentimentSource] : null;
}
