import { describe, expect, it } from "vitest";
import { chatSentimentSourceLabel, sentimentSourceLabel } from "./sentimentSource";

describe("sentimentSourceLabel (rehearsal defect #5)", () => {
  it("names each declared source", () => {
    expect(sentimentSourceLabel("AZURE_OPENAI")).toBe("Generated by Azure OpenAI");
    expect(sentimentSourceLabel("BEDROCK")).toBe("Generated by Amazon Bedrock");
    expect(sentimentSourceLabel("RULE_BASED")).toBe("Rule-based text (no AI model)");
  });

  it.each([[null], [undefined], [""], ["OPENAI"], ["toString"], ["__proto__"]])(
    "makes no claim for %p",
    (source) => {
      expect(sentimentSourceLabel(source as string | null | undefined)).toBeNull();
    },
  );
});

describe("chatSentimentSourceLabel (rehearsal defect #5: chat wording)", () => {
  it("scopes the source to the sentiment and names where the price and change come from", () => {
    expect(chatSentimentSourceLabel("AZURE_OPENAI")).toBe(
      "Sentiment generated by Azure OpenAI; price and change from stored market data",
    );
    expect(chatSentimentSourceLabel("BEDROCK")).toBe(
      "Sentiment generated by Amazon Bedrock; price and change from stored market data",
    );
    expect(chatSentimentSourceLabel("RULE_BASED")).toBe(
      "Rule-based sentiment (no AI model); price and change from stored market data",
    );
  });

  it.each([[null], [undefined], [""], ["OPENAI"], ["toString"], ["__proto__"]])(
    "makes no claim for %p",
    (source) => {
      expect(chatSentimentSourceLabel(source as string | null | undefined)).toBeNull();
    },
  );
});
