spring:
  application:
    name: insight-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: insight-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8083

logging:
  level:
    org.springframework.kafka: INFO
